#!/usr/bin/env python3
"""
Generates cases.csv for the NetSage AI project.
34 Packet-Tracer-style troubleshooting cases across VLAN, Gateway, DHCP,
DNS, Routing, ACL, NAT, and Wireless fault categories.
"""
import csv

CASES = [
    # ---------------- VLAN (6) ----------------
    dict(case_id="C001", category="VLAN", severity="High",
         symptom="PC1 (VLAN 10) cannot ping PC2 (VLAN 10) on the same switch.",
         topology_note="SW1 access ports Fa0/1 (PC1) and Fa0/2 (PC2), both intended for VLAN 10.",
         show_output="SW1# show vlan brief\nVLAN Name    Status  Ports\n10   Sales   active  Fa0/1\n20   HR      active  Fa0/2\n\nSW1# show interfaces fa0/2 switchport\nAdministrative Mode: static access\nOperational Mode: static access\nAccess Mode VLAN: 20 (HR)",
         expected_fault="Fa0/2 was assigned to VLAN 20 instead of VLAN 10, so PC1 and PC2 are on different broadcast domains.",
         osi_layer="Layer 2", concept_tag="vlan-port-assignment"),
    dict(case_id="C002", category="VLAN", severity="Medium",
         symptom="Devices in VLAN 30 on SW2 cannot reach devices in VLAN 30 on SW1.",
         topology_note="SW1-SW2 connected via Gi0/1 trunk carrying VLANs 10,20,30.",
         show_output="SW1# show interfaces trunk\nPort    Mode   Encapsulation  Status       Native vlan\nGi0/1   on     802.1q         trunking     1\n\nVlans allowed on trunk: 10,20\nVlans allowed and active in management domain: 10,20",
         expected_fault="VLAN 30 is not included in the trunk's allowed VLAN list, so VLAN 30 traffic is being dropped at the trunk.",
         osi_layer="Layer 2", concept_tag="trunk-allowed-vlans"),
    dict(case_id="C003", category="VLAN", severity="Medium",
         symptom="A new PC plugged into SW3 Fa0/5 receives no DHCP address and cannot reach anything.",
         topology_note="Fa0/5 was recently reconfigured for a lab exercise.",
         show_output="SW3# show interfaces fa0/5 switchport\nAdministrative Mode: trunk\nOperational Mode: trunk\nNative VLAN: 1 (default)",
         expected_fault="Fa0/5 was left in trunk mode instead of being reset to a VLAN access port, so the end host's untagged frames are mishandled.",
         osi_layer="Layer 2", concept_tag="port-mode-misconfig"),
    dict(case_id="C004", category="VLAN", severity="Low",
         symptom="PC3 and PC4 are both in VLAN 10 but experience intermittent connectivity and duplicate-IP warnings.",
         topology_note="PC3 static IP 192.168.10.11/24; PC4 DHCP client in the VLAN 10 DHCP pool 192.168.10.10-192.168.10.50.",
         show_output="PC4> ipconfig\nIP Address: 192.168.10.11\nSubnet Mask: 255.255.255.0\n\n%DUPLICATE ADDRESS 192.168.10.11 detected on Fa0/1, sourced by 000A.4123.5678",
         expected_fault="PC3's static address overlaps the DHCP scope handed to PC4, producing an IP conflict, not a VLAN misconfiguration.",
         osi_layer="Layer 3", concept_tag="duplicate-ip-dhcp-overlap"),
    dict(case_id="C005", category="VLAN", severity="High",
         symptom="Inter-VLAN routing works for VLAN 10 and VLAN 20 but not VLAN 30 on router-on-a-stick.",
         topology_note="R1 Gi0/0 has three sub-interfaces for VLANs 10, 20, 30.",
         show_output="R1# show ip interface brief\nInterface           IP-Address      Status   Protocol\nGi0/0.10            192.168.10.1    up       up\nGi0/0.20            192.168.20.1    up       up\nGi0/0.30            unassigned      up       up",
         expected_fault="The VLAN 30 sub-interface (Gi0/0.30) has no IP address configured, so it cannot route for that VLAN.",
         osi_layer="Layer 3", concept_tag="router-on-a-stick-subinterface"),
    dict(case_id="C006", category="VLAN", severity="Medium",
         symptom="After a switch reload, several access ports revert to VLAN 1 and lose connectivity.",
         topology_note="SW4 configuration was not saved before the reload.",
         show_output="SW4# show vlan brief\nVLAN Name    Status  Ports\n1    default active  Fa0/3, Fa0/4, Fa0/5\n\nSW4# show running-config | include boot\n(no startup-config saved)",
         expected_fault="Running-config was never copied to startup-config, so VLAN assignments were lost on reload.",
         osi_layer="Layer 2", concept_tag="config-not-saved"),

    # ---------------- Gateway (4) ----------------
    dict(case_id="C007", category="Gateway", severity="High",
         symptom="PC gets an IP address but cannot ping its own default gateway.",
         topology_note="PC5 in VLAN 20, gateway should be SVI 192.168.20.1 on SW-MLS.",
         show_output="PC5> ipconfig\nIP Address: 192.168.20.15\nSubnet Mask: 255.255.255.0\nDefault Gateway: 192.168.20.254\n\nSW-MLS# show ip interface brief | include Vlan20\nVlan20    192.168.20.1    up      up",
         expected_fault="PC5 is configured with the wrong gateway address (192.168.20.254) instead of the real SVI address 192.168.20.1.",
         osi_layer="Layer 3", concept_tag="wrong-default-gateway"),
    dict(case_id="C008", category="Gateway", severity="High",
         symptom="Gateway ping fails for the entire VLAN 40 subnet after a maintenance window.",
         topology_note="VLAN 40 SVI on SW-MLS was being reconfigured last night.",
         show_output="SW-MLS# show ip interface brief | include Vlan40\nVlan40    192.168.40.1    administratively down    down",
         expected_fault="The VLAN 40 SVI is administratively shut down, so no host in that VLAN can reach its gateway.",
         osi_layer="Layer 3", concept_tag="svi-shutdown"),
    dict(case_id="C009", category="Gateway", severity="Medium",
         symptom="PC6 can ping its gateway but not any other subnet.",
         topology_note="PC6 gateway 192.168.50.1 responds to ping; router has multiple networks configured.",
         show_output="PC6> ipconfig\nSubnet Mask: 255.255.255.0\n\nR2# show ip interface brief\nGi0/1    192.168.50.1   up   up",
         expected_fault="This is not actually a gateway fault — the gateway itself is reachable, so the issue lies further upstream (routing), and the case is a distractor for OSI-layer identification.",
         osi_layer="Layer 3", concept_tag="gateway-reachable-distractor"),
    dict(case_id="C010", category="Gateway", severity="Medium",
         symptom="Laptop with a manually configured IP cannot reach the gateway, but DHCP clients on the same switch work fine.",
         topology_note="Laptop assigned 192.168.60.20/25 while the VLAN uses a /24 with gateway 192.168.60.1.",
         show_output="Laptop> ipconfig\nIP Address: 192.168.60.20\nSubnet Mask: 255.255.255.128\nDefault Gateway: 192.168.60.1",
         expected_fault="The laptop's /25 mask places the gateway (192.168.60.1, in the .0-.127 half if using second half incorrectly) outside its calculated subnet, so ARP for the gateway never resolves.",
         osi_layer="Layer 3", concept_tag="subnet-mask-mismatch"),

    # ---------------- DHCP (4) ----------------
    dict(case_id="C011", category="DHCP", severity="High",
         symptom="All PCs in VLAN 10 fail to receive an IP address via DHCP.",
         topology_note="DHCP server is a Cisco router (R1) with pool SALES_POOL for 192.168.10.0/24.",
         show_output="R1# show ip dhcp pool\nPool SALES_POOL :\nUtilization mark (high/low)    : 100 / 0\nSubnet size (first/last)      : 0 / 0\nTotal addresses                : 0\nLeased addresses               : 0\n\nR1# show run | section dhcp\nip dhcp excluded-address 192.168.10.1 192.168.10.254",
         expected_fault="The excluded-address range covers the entire pool (192.168.10.1-254), leaving zero usable leasable addresses.",
         osi_layer="Layer 3", concept_tag="dhcp-excluded-range-too-wide"),
    dict(case_id="C012", category="DHCP", severity="High",
         symptom="Hosts on a remote VLAN across a router cannot get DHCP addresses, while the local VLAN with the DHCP server works.",
         topology_note="Central DHCP server on R1; remote VLAN 20 is one hop away via SW-MLS SVI Vlan20.",
         show_output="SW-MLS# show run interface vlan 20\ninterface Vlan20\n ip address 192.168.20.1 255.255.255.0\n(no ip helper-address configured)",
         expected_fault="Vlan20's SVI is missing an 'ip helper-address' pointing at the DHCP server, so broadcast DHCP requests never reach it across the router boundary.",
         osi_layer="Layer 3", concept_tag="missing-dhcp-relay"),
    dict(case_id="C013", category="DHCP", severity="Medium",
         symptom="A PC receives an IP address, but it is from the wrong subnet compared to the rest of its VLAN.",
         topology_note="VLAN 30 should use pool 192.168.30.0/24; a second overlapping pool exists.",
         show_output="R1# show ip dhcp pool\nPool GUEST_POOL :\n Network 192.168.30.0 mask 255.255.255.0\nPool OLD_LAB_POOL :\n Network 192.168.30.0 mask 255.255.254.0",
         expected_fault="Two DHCP pools advertise overlapping network 192.168.30.0 ranges; the router is handing out leases from the stale OLD_LAB_POOL.",
         osi_layer="Layer 3", concept_tag="overlapping-dhcp-pools"),
    dict(case_id="C014", category="DHCP", severity="Low",
         symptom="One specific PC never gets an IP even though others on the same switch do.",
         topology_note="PC7 is plugged into Fa0/8 on SW1, same VLAN as working PCs.",
         show_output="SW1# show interfaces fa0/8 status\nPort     Status       Vlan       Duplex  Speed\nFa0/8    err-disabled 10         auto    auto",
         expected_fault="Fa0/8 is in an err-disabled state (likely from a port-security violation), so no traffic including DHCP requests passes.",
         osi_layer="Layer 1", concept_tag="err-disabled-port"),

    # ---------------- DNS (4) ----------------
    dict(case_id="C015", category="DNS", severity="Medium",
         symptom="PC can ping the web server's IP address directly but browsing by hostname (www.lab.local) fails.",
         topology_note="DNS server 192.168.1.53 should resolve www.lab.local.",
         show_output="PC8> ipconfig /all\nDNS Servers: 192.168.1.53\n\nPC8> nslookup www.lab.local\nDNS request timed out.",
         expected_fault="Name resolution is failing at the application/DNS layer even though IP-layer reachability to the server itself is fine; the DNS service or record is the fault, not routing.",
         osi_layer="Layer 7", concept_tag="dns-resolution-failure"),
    dict(case_id="C016", category="DNS", severity="Medium",
         symptom="Half the office can resolve www.lab.local, the other half cannot, despite identical VLANs.",
         topology_note="Two DHCP scopes exist for the same VLAN with different DNS server settings.",
         show_output="R1# show ip dhcp pool\nPool A:\n dns-server 192.168.1.53\nPool B:\n dns-server 8.8.8.8",
         expected_fault="Pool B is handing out a public DNS server that has no record for the internal www.lab.local zone, so only Pool A clients resolve it.",
         osi_layer="Layer 7", concept_tag="wrong-dns-server-assigned"),
    dict(case_id="C017", category="DNS", severity="Low",
         symptom="nslookup for www.lab.local returns NXDOMAIN even though the DNS server is reachable.",
         topology_note="DNS server has zone lab.local configured.",
         show_output="DNS-SRV# show run | section dns\nip dns server\nip host mail.lab.local 192.168.1.20\n(no host entry for www.lab.local)",
         expected_fault="No host record exists for www.lab.local on the DNS server; only mail.lab.local was configured.",
         osi_layer="Layer 7", concept_tag="missing-dns-record"),
    dict(case_id="C018", category="DNS", severity="Medium",
         symptom="Web browsing is extremely slow to start but eventually loads on every site.",
         topology_note="Primary DNS server is unreachable; secondary is configured but far away.",
         show_output="PC9> ipconfig /all\nDNS Servers: 192.168.1.53, 4.2.2.2\n\nPC9> ping 192.168.1.53\nRequest timed out. (4/4 lost)",
         expected_fault="The primary DNS server 192.168.1.53 is down, forcing every lookup to time out and fail over to the slow secondary resolver.",
         osi_layer="Layer 7", concept_tag="primary-dns-unreachable"),

    # ---------------- Routing (6) ----------------
    dict(case_id="C019", category="Routing", severity="High",
         symptom="PC in VLAN 10 (192.168.10.0/24) cannot reach server in VLAN 30 (192.168.30.0/24); gateway ping works.",
         topology_note="R1 connects VLAN10, VLAN20, VLAN30 via sub-interfaces; static routing in use.",
         show_output="R1# show ip route\nC    192.168.10.0/24 is directly connected, Gi0/0.10\nC    192.168.20.0/24 is directly connected, Gi0/0.20\n(no route to 192.168.30.0/24)",
         expected_fault="No route/sub-interface exists for VLAN 30 on R1, so traffic destined there has no path even though the gateway itself answers pings.",
         osi_layer="Layer 3", concept_tag="missing-route"),
    dict(case_id="C020", category="Routing", severity="High",
         symptom="Branch office cannot reach HQ servers; local branch traffic works fine.",
         topology_note="Branch router R-BR connects to HQ router R-HQ over a serial WAN link using OSPF area 0.",
         show_output="R-BR# show ip ospf neighbor\n(no output)\n\nR-BR# show ip interface brief\nSerial0/0/0   10.0.0.2   up   down",
         expected_fault="Serial0/0/0's line protocol is down (likely a clock rate or encapsulation mismatch), so no OSPF neighbor forms and no HQ routes are learned.",
         osi_layer="Layer 1/2", concept_tag="wan-link-down-ospf"),
    dict(case_id="C021", category="Routing", severity="Medium",
         symptom="Traffic to the internet works, but traffic between two internal VLANs across two routers fails.",
         topology_note="R1 and R2 are connected; both run OSPF but internal VLAN 40 on R2 isn't reachable from R1's side.",
         show_output="R1# show ip route ospf\nO    192.168.10.0/24 [110/2] via 10.0.0.2\n(no OSPF route to 192.168.40.0/24)\n\nR2# show run | section router ospf\nrouter ospf 1\n network 192.168.10.0 0.0.0.255 area 0\n(network 192.168.40.0 not advertised)",
         expected_fault="R2's OSPF process never advertises the 192.168.40.0/24 network statement, so R1 has no route to it.",
         osi_layer="Layer 3", concept_tag="ospf-network-statement-missing"),
    dict(case_id="C022", category="Routing", severity="High",
         symptom="Default route to the internet is missing; internal traffic is fine but nothing external resolves.",
         topology_note="R1 should forward unknown traffic to ISP router via Gi0/2.",
         show_output="R1# show ip route\nGateway of last resort is not set\nC    192.168.10.0/24 is directly connected, Gi0/0.10",
         expected_fault="No default route (ip route 0.0.0.0 0.0.0.0) is configured, so R1 drops all traffic to unknown external destinations.",
         osi_layer="Layer 3", concept_tag="missing-default-route"),
    dict(case_id="C023", category="Routing", severity="Medium",
         symptom="Two routers using EIGRP fail to become neighbors even though the link is physically up.",
         topology_note="R1 AS 100, R2 AS 200 configured for EIGRP on the same link.",
         show_output="R1# show ip eigrp neighbors\n(no neighbors)\n\nR1# show run | section eigrp\nrouter eigrp 100\n\nR2# show run | section eigrp\nrouter eigrp 200",
         expected_fault="R1 and R2 are configured with mismatched EIGRP autonomous system numbers (100 vs 200), preventing adjacency.",
         osi_layer="Layer 3", concept_tag="eigrp-as-mismatch"),
    dict(case_id="C024", category="Routing", severity="Low",
         symptom="Route to a subnet exists but traceroute shows a routing loop between two routers.",
         topology_note="Static routes configured on R1 and R2 as a redundant backup path.",
         show_output="R1# show ip route static\nS    192.168.90.0/24 [1/0] via 10.0.0.2\n\nR2# show ip route static\nS    192.168.90.0/24 [1/0] via 10.0.0.1",
         expected_fault="Both routers point the same destination network back at each other via static routes, creating a routing loop instead of reaching the real subnet.",
         osi_layer="Layer 3", concept_tag="static-route-loop"),

    # ---------------- ACL (4) ----------------
    dict(case_id="C025", category="ACL", severity="High",
         symptom="PC gets an IP but cannot reach server in VLAN 30; gateway ping works.",
         topology_note="R1 has an inbound ACL on Gi0/0.10 intended to block only Telnet to the server.",
         show_output="R1# show access-lists\nExtended IP access list BLOCK_TELNET\n 10 deny tcp any host 192.168.30.10 eq 23\n 20 deny ip any any\n 30 permit ip any any (0 matches)",
         expected_fault="Line 20 ('deny ip any any') sits above the intended broad permit and blocks all IP traffic to the server, not just Telnet.",
         osi_layer="Layer 3/4", concept_tag="acl-overbroad-deny"),
    dict(case_id="C026", category="ACL", severity="Medium",
         symptom="Guest Wi-Fi users can reach the internal file server, which should be isolated.",
         topology_note="Guest VLAN 99 should be blocked from VLAN 10 (internal) by an ACL on the SVI.",
         show_output="SW-MLS# show run interface vlan99\ninterface Vlan99\n ip address 192.168.99.1 255.255.255.0\n(no access-group applied)",
         expected_fault="An ACL to deny guest-to-internal traffic exists in the config but was never applied to the Vlan99 interface with 'ip access-group', so guests reach internal resources.",
         osi_layer="Layer 3", concept_tag="acl-not-applied"),
    dict(case_id="C027", category="ACL", severity="Medium",
         symptom="Server admins cannot SSH into the server from the management VLAN even though it worked yesterday.",
         topology_note="ACL MGMT_ACCESS should permit SSH from 192.168.5.0/24 to the server.",
         show_output="R1# show access-lists MGMT_ACCESS\nExtended IP access list MGMT_ACCESS\n 10 permit tcp 192.168.5.0 0.0.0.255 host 192.168.30.10 eq 22\n\nInterface Gi0/0.30\n ip access-group MGMT_ACCESS in",
         expected_fault="The ACL only permits SSH (22) inbound on Gi0/0.30 toward the server subnet, but admins are coming from a newly renumbered 192.168.6.0/24 subnet not covered by the ACL, so it silently falls to the implicit deny.",
         osi_layer="Layer 3/4", concept_tag="acl-source-not-covered"),
    dict(case_id="C028", category="ACL", severity="Low",
         symptom="Ping between two VLANs works but a specific TCP-based lab application on port 8080 fails.",
         topology_note="An ACL was added recently to harden the network between VLAN 10 and VLAN 40.",
         show_output="R1# show access-lists\nExtended IP access list HARDEN\n 10 permit icmp any any\n 20 deny tcp any any eq 8080\n 30 permit ip any any",
         expected_fault="Line 20 explicitly denies TCP port 8080, blocking the lab application while ICMP and other IP traffic are still permitted.",
         osi_layer="Layer 4", concept_tag="acl-specific-port-block"),

    # ---------------- NAT (4) ----------------
    dict(case_id="C029", category="NAT", severity="High",
         symptom="Internal PCs cannot reach the internet even though they have valid private IPs and a default route.",
         topology_note="R1 performs PAT (NAT overload) toward the ISP using interface Gi0/2.",
         show_output="R1# show ip nat statistics\nTotal active translations: 0\n\nR1# show run | include nat\nip nat inside source list 1 interface GigabitEthernet0/2 overload\n(interface Gi0/0.10 missing 'ip nat inside')",
         expected_fault="The internal-facing sub-interface Gi0/0.10 is missing the 'ip nat inside' command, so the router never recognizes that traffic as needing translation.",
         osi_layer="Layer 3", concept_tag="nat-inside-not-applied"),
    dict(case_id="C030", category="NAT", severity="Medium",
         symptom="Internet access works for most PCs, but connections drop after about 40 concurrent users are online.",
         topology_note="PAT overload configured with a single public IP.",
         show_output="R1# show ip nat statistics\nTotal active translations: 4058 (500 static, 3558 dynamic)\nHits: 89000 Misses: 612",
         expected_fault="The NAT overload port/address table is exhausting available translation slots under peak load; PAT capacity, not connectivity, is the constraint.",
         osi_layer="Layer 3/4", concept_tag="nat-overload-exhaustion"),
    dict(case_id="C031", category="NAT", severity="Medium",
         symptom="External users cannot reach the internal web server via the company's public IP.",
         topology_note="A static NAT entry should map public 203.0.113.10 to internal 192.168.30.10 on port 80.",
         show_output="R1# show ip nat translations\n(no static entries listed)\n\nR1# show run | include nat\nip nat inside source static tcp 192.168.30.10 8080 203.0.113.10 80",
         expected_fault="The static NAT rule maps internal port 8080 instead of 80, so the server (listening on 80) never receives the translated traffic.",
         osi_layer="Layer 4", concept_tag="static-nat-port-mismatch"),
    dict(case_id="C032", category="NAT", severity="Low",
         symptom="Some internal servers with static NAT work externally, one new server does not.",
         topology_note="New server 192.168.30.20 was just added; static NAT was configured for it.",
         show_output="R1# show run | include 192.168.30.20\nip nat inside source static 192.168.30.20 203.0.113.20\n\nR1# show ip interface brief\nGi0/0.30    192.168.30.1    up    up  (ip nat inside not present in config)",
         expected_fault="The static NAT rule exists, but the VLAN 30 sub-interface itself was never marked 'ip nat inside', so the translation never triggers for any host on that VLAN, including the new server.",
         osi_layer="Layer 3", concept_tag="nat-inside-missing-on-interface"),

    # ---------------- Wireless (4) ----------------
    dict(case_id="C033", category="Wireless", severity="Medium",
         symptom="Laptop sees the corporate SSID but fails to associate, showing 'authentication error'.",
         topology_note="WLC configured with WPA2-PSK for SSID CORP_WIFI.",
         show_output="WLC# show wlan CORP_WIFI\nSecurity: WPA2 PSK\nPassphrase: (configured, hash mismatch reported by client)\n\nLaptop> wireless status\nAuthentication: Failed - incorrect pre-shared key",
         expected_fault="The pre-shared key configured on the laptop does not match the WLC's WPA2-PSK passphrase.",
         osi_layer="Layer 2", concept_tag="wifi-psk-mismatch"),
    dict(case_id="C034", category="Wireless", severity="Medium",
         symptom="Guest Wi-Fi devices associate fine but never get an IP address.",
         topology_note="Guest SSID maps to VLAN 99 on the WLC, trunked to SW-MLS.",
         show_output="SW-MLS# show interfaces trunk\nVlans allowed on trunk: 1,10,20,30\n(VLAN 99 not listed)",
         expected_fault="VLAN 99 (the guest WLAN's VLAN) is not permitted on the trunk between the WLC/AP switch and the distribution switch, so DHCP broadcasts for guests never reach the DHCP server.",
         osi_layer="Layer 2", concept_tag="wireless-vlan-not-trunked"),
    dict(case_id="C035", category="Wireless", severity="Low",
         symptom="Users in the far corner of the warehouse report no Wi-Fi signal, while the rest of the building is fine.",
         topology_note="A single AP (AP-WH1) was placed to cover the whole warehouse floor.",
         show_output="AP-WH1# show controllers dot11radio 0\nTransmit Power: 1 (1 mW)\nCoverage radius (est.): ~15m\n\nSite survey: warehouse floor is 60m x 40m",
         expected_fault="The AP's transmit power is set far below what the warehouse footprint requires, so signal simply does not reach the far corner — a Layer 1 RF coverage problem, not a configuration bug.",
         osi_layer="Layer 1", concept_tag="wifi-insufficient-tx-power"),
    dict(case_id="C036", category="Wireless", severity="Medium",
         symptom="Wireless clients connect successfully but throughput is far below expected and file transfers frequently stall.",
         topology_note="Two nearby APs (AP-1, AP-2) serve overlapping areas on the same floor.",
         show_output="AP-1# show controllers dot11radio 0 | include Channel\nChannel: 6\n\nAP-2# show controllers dot11radio 0 | include Channel\nChannel: 6",
         expected_fault="AP-1 and AP-2 are both set to channel 6 with overlapping coverage, causing co-channel interference that degrades throughput for clients in the overlap zone.",
         osi_layer="Layer 1", concept_tag="wifi-channel-overlap"),
]

FIELDNAMES = ["case_id", "category", "severity", "symptom", "topology_note",
              "show_command_output", "expected_fault", "osi_layer", "concept_tag"]

with open("/home/claude/netsage/data/cases.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
    writer.writeheader()
    for c in CASES:
        writer.writerow({
            "case_id": c["case_id"],
            "category": c["category"],
            "severity": c["severity"],
            "symptom": c["symptom"],
            "topology_note": c["topology_note"],
            "show_command_output": c["show_output"],
            "expected_fault": c["expected_fault"],
            "osi_layer": c["osi_layer"],
            "concept_tag": c["concept_tag"],
        })

print(f"Wrote {len(CASES)} cases to cases.csv")
